### ISSUE TITLE
Why to randomize ict examples in VT? & other bugs

### ISSUE THREAD

**Issue by huangyuxiang03** [NVIDIA/Star-Attention#2] opened 2024-12-04 12:16 UTC
Hi,

Thanks for your great work! This is inspiring on enhancing long context inference's efficiency.

What is the purpose to randomize ict examples in VT of RULER? I have checked the original implementation of RULER, and this is not included. When I try to replicate the Llama-3.1-8B-instruct experiments, VT score remains very low (which is very different from your paper and the original RULER result). Then I track down this problem and find that this randomization seems to replace `<|eot_id|><|start_header_id|>assistant<|end_header_id|>` into some randomized string. Is this correct?

When this is removed (just like the original RULER's implementation), the VT score seems to be normal.

Thanks.

**Comment by huangyuxiang03** [comment] 2024-12-04 13:06
After fixing this problem, I generated 10 entries of VT (16K length), tested on Llama-3.1-8B-instruct. The result of full attention is 98, but when I try to run RingAttention with 8 GPUs, the score drops to 46. 

I'm using the following command
```bash
python $SCRIPT -p $MODEL_PATH -n $MODEL_NAME -a ring -pc $PROMPT_CONFIG -l 16384 -np 8
```

When running StarAttention, similar phenomenon is observed. The score of running on 2, 4, 8 GPUs are 94, 82, 24 correspondingly. However, since StarAttention is a heuristic attention algorithm, this is reasonable, as when running on 8 GPUs with a block size of 2K, the attention pattern basically degrade to StreamingLLM. 

But RingAttention is a precise attention algorithm, there shouldn't be such degredation. Am I setting something wrong?

More information:
I am getting lots of repetitions in the setting of ring attention with 8 GPUs
```
The word Norman comes from the French words Normans/Normanz, plural of Normant, modern French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French French
```

**Comment by shan18** [comment] 2024-12-04 16:41
Thanks for pointing out the issue. I'll take a look into why this bug is happening because we have also used the exact same script to generate the dataset.

Meanwhile will it be possible for you to share the first ~350 characters of `input_query` and `input_context` of any one sample of the dataset that you generated?
For example, here's a sample from the dataset that we have:
```
"input_context": "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n Memorize and track the chain(s) of variable assignment hidden in the following text. The grass is green. The sky is blue. The sun is yellow. Here we go. There ...

"input_query": "Question: Find all variables that are assigned the value 42606 in the text above.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n Answer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 42606, they are: "
```

This would help in debugging this issue.

**Comment by huangyuxiang03** [comment] 2024-12-04 16:59
Thanks for your timely reply. The prefix of the generated input is like this:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n Memorize and track the chain(s) of variable assignment hidden in the following text. The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR IBW = 64886 The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR TAO = VAR IBW  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR PSH = VAR TAO  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR FFO = VAR PSH  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR GOY = VAR FFO  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n Question: Find all variables that are assigned the value 64886 in the text Answer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 64886, they are: ENGFWDMBKKNKGICLJNVBJPBBUPRFFXHXFETTTXSSKGIHMQIJWMUSTIF\n\n IBW TAO PSH FFO GOY\n\n\n\nMemorize and track the chain(s) of variable assignment hidden in the following text.\n\nThe grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. 
```

There is a randomized string `ENGFWDMBKKNKGICLJNVBJPBBUPRFFXHXFETTTXSSKGIHMQIJWMUSTIF` inside, replacing `<|eot_id|><|start_header_id|>assistant<|end_header_id|>`. 

Also, I think the performance degredation of ring attention baseline is not caused by this issue. I have observed similar phenomenon with this problem fixed.

**Comment by shan18** [comment] 2024-12-04 18:20
When you generate the dataset, it will create a file called `validation.jsonl`. From that jsonl file, can you please separately share the value of the `input_query` key from the 1st sample and also the first 300 characters from the key `input_context`?

Also the reason why our ruler code has the `randomize_icl` function because if this function is not there, sometimes the few shot examples have some bias which lead to very high scores for variable tracking. This issue has been identified by the authors of RULER as well. They did not push this fix to their github repo yet but shortly they'll be adding this fix to their script as well.

**Comment by huangyuxiang03** [comment] 2024-12-05 01:47
Input query:
```
"input_query": "Question: Find all variables that are assigned the value 42606 in the text above. Answer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 42606, they are: <|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n", "outputs": ["DZGXO", "PUVGW", "ZNKHO", "PTERO", "BIQJN"]
```

input context:
```
"input_context": "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n Memorize and track the chain(s) of variable assignment hidden in the following text. The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR IBW = 64886 The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR TAO = VAR IBW  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR PSH = VAR TAO  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR FFO = VAR PSH  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n VAR GOY = VAR FFO  The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n Question: Find all variables that are assigned the value 64886 in the text Answer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 64886, they are: ENGFWDMBKKNKGICLJNVBJPBBUPRFFXHXFETTTXSSKGIHMQIJWMUSTIF\n\n IBW TAO PSH FFO GOY\n\n\n\nMemorize and track the chain(s) of variable assignment hidden in the following text.\n\nThe grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue. The sun is yellow. Here we go. There and back again.\n The grass is green. The sky is blue.
```

**Comment by huangyuxiang03** [comment] 2024-12-05 08:16
I tried to debug for the reason why RingAttention has large performance degredation. It seems like there is a large error between RingAttention and Dense. I tried to compare the kv cache of the same sequence over 16K context on 8 GPUs (2K for each), and the error is very large. Even the first block on GPU 0 exhibits a large error. I did not manage to find out the cause, and here are some logs

left: max abs error, right: max abs value in the corresponding tensor

```
layer 0
k: 0.125 / 10.375
v: 0.001953125 / 0.4609375
layer 1
k: 0.125 / 11.0625
v: 0.0078125 / 1.5625
layer 2
k: 0.21875 / 16.25
v: 0.02734375 / 1.875
layer 3
k: 0.25 / 19.75
v: 0.046875 / 1.9609375
layer 4
k: 0.25 / 19.625
v: 0.041015625 / 1.734375
layer 5
k: 0.375 / 16.875
v: 0.0634765625 / 1.9296875
layer 6
k: 0.4375 / 17.125
v: 0.138671875 / 2.984375
layer 7
k: 0.9375 / 21.0
v: 0.1630859375 / 2.328125
layer 8
k: 1.8125 / 18.5
v: 0.4453125 / 2.15625
layer 9
k: 3.421875 / 20.75
v: 0.953125 / 2.59375
layer 10
k: 7.59375 / 22.625
v: 1.7890625 / 2.34375
layer 11
k: 11.625 / 21.125
v: 3.6875 / 3.34375
layer 12
k: 7.5 / 20.875
v: 2.25 / 2.1875
layer 13
k: 8.5 / 20.5
v: 2.34375 / 2.3125
layer 14
k: 12.375 / 22.25
v: 1.921875 / 2.890625
layer 15
k: 8.25 / 17.25
v: 2.3125 / 2.65625
layer 16
k: 11.25 / 22.0
v: 1.671875 / 2.34375
layer 17
k: 10.375 / 19.75
v: 1.9375 / 2.125
layer 18
k: 9.25 / 18.625
v: 2.03125 / 2.9375
layer 19
k: 9.75 / 19.125
v: 1.703125 / 3.234375
layer 20
k: 9.75 / 20.25
v: 1.578125 / 2.71875
layer 21
k: 9.75 / 20.75
v: 2.171875 / 3.25
layer 22
k: 9.8125 / 21.375
v: 2.09375 / 3.21875
layer 23
k: 8.75 / 22.875
v: 1.6171875 / 3.328125
layer 24
k: 8.75 / 23.375
v: 2.078125 / 4.75
layer 25
k: 8.0625 / 25.0
v: 2.40625 / 3.890625
layer 26
k: 8.1875 / 23.25
v: 2.0625 / 3.421875
layer 27
k: 8.375 / 23.125
v: 2.8125 / 4.28125
layer 28
k: 7.8125 / 23.375
v: 2.6875 / 4.4375
layer 29
k: 10.125 / 34.5
v: 2.6875 / 5.90625
layer 30
k: 8.5625 / 22.0
v: 4.3125 / 4.96875
layer 31
k: 4.75 / 16.75
v: 3.125 / 6.34375
```

I'm pretty sure there is something going wrong. The first block shouldn't have such large error. I set up my environment following `requirements.txt`, and the torch version should be same as what you have been using. 

I deeply appreciate your effort on providing the code. Could you take a look into this? Thank you very much.

**Comment by huangyuxiang03** [comment] 2024-12-05 08:22
In fact, there are other problems. For examples, when using Llama-3.1-8B-instruct, there is `|` in the stop word, and linux would fail to execute the benchmark code since the stop words are not wrapped in `""`. And there is no `--benchmark synthetic ` in `ruler/data/prepare.py`'s flags. 

I'm still trying to get everything correct, and I think I can create a merge request once I get the bugs fixed.

Update: The error in Ring Attention seems caused by flash attention. It is weird that Llama-3.1-8B-instruct has a tremendous precision error when using bfloat16 and flash attention. I've tried other models, such as Llama-3.2-1B-intruct, this problem seems to be alleviated. However, I cannot repreduce the baseline (Ring Attention) in your paper, so I think I'm still getting someting wrong. Sorry for sending too many messages, as I've been trying all day finding the bug. Could you provide more information about the environment to conduct the experiments?

**Comment by shan18** [comment] 2024-12-06 00:09
Hi, the input query that you shared looks different.

What you shared:
```
"input_query": "Question: Find all variables that are assigned the value 42606 in the text above. Answer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 42606, they are: <|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
```

But how it should look like:
```
"input_query": "Question: Find all variables that are assigned the value 42606 in the text above.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAnswer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 42606, they are:"
```

Notice the position of: `<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n`
this header should come before the answer_prefix.

Can you please try it with this template once in your samples? I think your issues should be resolved with this.

**Comment by shan18** [comment] 2024-12-06 00:17
Hi, I think I found the issue. There was a bug in the code that I missed pushing to this main branch:

In the old code, the input query looks like this:
```
"input_query": "Question: Find all variables that are assigned the value 42606 in the text above. Answer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 42606, they are: <|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
```

But now it should look like:
```
"input_query": "Question: Find all variables that are assigned the value 42606 in the text above.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAnswer: According to the chain(s) of variable assignment in the text above, 5 variables are assgined the value 42606, they are:"
```

Notice the position of: `<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n`
this header should come before the answer_prefix. This is same as what's there in the original RULER repo, the template header comes before the answer prefix.

Can you please try it with this template once in your samples? I think your issues should be resolved with this.

The issue was fixed with this commit: b4c4624a6f0808981a73e58d080d758148c2adff

**Comment by huangyuxiang03** [comment] 2024-12-06 03:17
Thanks for your bug fix. The output seems to have the correct format now. But there is still a performance drop when running the ring attention baseline. Running vt with 16K context divided on 8 GPUs can only get a ~60 accuracy, and this suppose to be ~100 according to the original ruler's result.

**Comment by shan18** [comment] 2024-12-06 05:01
I pushed a few more fixes to the `run_ruler.py` script. There were quite a few syntax errors when running this, I have fixed them now.

Regarding your issue with ring attention, I have been able to to reproduce your issue now. When using 8 GPUs, I'm getting ~67 for variable tracking but when I use 4 GPUs, I get 94.
To reproduce, please pull from the main branch and reinstall the dependencies from `requirements.txt`. The command with which I get 94 is:
```
python run_ruler.py \
  -p <path to Llama-3.1-8B-Instruct> \
  -n llama8b \
  -a ring \
  -pc llama3 \
  -l 16384 \
  -t vt \
  --num_samples_per_task 20 \
  -np 4
```

I run this script on a machine with 8 GPUs, so when I set `-np 4`, it will assign 2 GPUs to each process.

With this command I get:
```
       0     1
0  Tasks    vt
1  Score  94.0
2  Nulls  0/20
```

I'll take a look at this issue now and fix this soon. It should be ~99.

**Comment by huangyuxiang03** [comment] 2024-12-06 11:56
I reimplemented the ring attention-related part using the original ring-flash-attention repo, and running 16K on 8 GPUs with Llama-3.1-8B-instruct is ok now. Both dense and ring attn gives 92 on vt. 

I tried to find out the reason why the ring attention implemented in this repo has such problem, but I failed. I reimplemented it in ![star-attention-debug](https://github.com/huangyuxiang03/Star-Attention) and ![ring-flash-attn-debug](https://github.com/huangyuxiang03/ring-flash-attention). I think this might be useful for you to debug. Install the ring-flash-attn-debug first, then run `bash launch.sh` can reproduce the results.

My implementation is pretty coarse, as I'm trying to solve this problem as soon as possible. Apologies for inreadabilities!

It seems like the performance drop is not caused by dataset implementation, but related to the model implementation. Since I don't know where the problem is, I cannot distinguish whether the performance drop of Star-Attention is caused by some bugs or caused by the reason that you have explained in the paper. Thus I think it is still pretty important to find out where the problem is. Thanks for your cooperation!

**Comment by huangyuxiang03** [comment] 2024-12-07 16:04
Here are my updates:

I think there are still problems in model implementation. I tested my implementation of ring attention on 128K qa1 with 8 GPUs on Llama-3.1-8B-instruct, and I got a 78.2 acc (This number reported in your paper is 76.0), showing that ring attention should work correctly with Llama-3.1-8B-instruct. But when I test 128K vt on 4 gpus for star attention, there is only a 52.8 acc (This number reported in your paper is 62.8). Thus I think there is still something wrong, and the bug both affect ring attention and star attention.

**Comment by nienie5126** [comment] 2024-12-17 11:31
> Here are my updates:
> 
> I think there are still problems in model implementation. I tested my implementation of ring attention on 128K qa1 with 8 GPUs on Llama-3.1-8B-instruct, and I got a 78.2 acc (This number reported in your paper is 76.0), showing that ring attention should work correctly with Llama-3.1-8B-instruct. But when I test 128K vt on 4 gpus for star attention, there is only a 52.8 acc (This number reported in your paper is 62.8). Thus I think there is still something wrong, and the bug both affect ring attention and star attention.

Hi~ May I ask what speedup has been achieved in your experiment? Recently, when I ran the niah_single task on 8*A800 GPUs, I found that the inference time for one sample was 20 seconds(context length is 16K and np is 8), while the time of ring attention was 10 seconds. I'm wondering what might be the reasons for this or did you meet the same issue before? Thanks~

**Comment by shan18** [comment] 2024-12-17 13:05
> Hi~ May I ask what speedup has been achieved in your experiment? Recently, when I ran the niah_single task on 8*A800 GPUs, I found that the inference time for one sample was 20 seconds(context length is 16K and np is 8), while the time of ring attention was 10 seconds. I'm wondering what might be the reasons for this or did you meet the same issue before? Thanks~

Hi, I can share the inference speedup details. But can you please share this comment in a separate issue. It would be great if we could have separate topics in separate issue threads.

**Comment by nienie5126** [comment] 2024-12-18 01:31
> > Hi~ May I ask what speedup has been achieved in your experiment? Recently, when I ran the niah_single task on 8*A800 GPUs, I found that the inference time for one sample was 20 seconds(context length is 16K and np is 8), while the time of ring attention was 10 seconds. I'm wondering what might be the reasons for this or did you meet the same issue before? Thanks~
> 
> Hi, I can share the inference speedup details. But can you please share this comment in a separate issue. It would be great if we could have separate topics in separate issue threads.

Thank you for your reply, I have opened a new issue and the link is https://github.com/NVIDIA/Star-Attention/issues/3

**Comment by shan18** [comment] 2024-12-28 23:40
@huangyuxiang03 the issue has been resolved now. Sorry for the delay. The PR #5 contains the explanation of the bug and has been merged to main branch.

**Closed as completed** 2024-12-28 23:39 UTC
Labels: bug

**Comment by huangyuxiang03** [comment] 2024-12-29 02:37
Thanks for fixing this bug!
